### ISSUE TITLE
Error when running searchlight function 

### ISSUE THREAD

**Issue by taotaohe** [mekman/mansfield#1]
Hi @mekman,

There is an error when running `searchlight` function in the `mansfield.py`, see below:

Line 48: TypeError: 'numpy.float64' object cannot be interpreted as an integer.

I think you need to change `fmri_img = np.zeros((shape))` to `fmri_img = np.zeros((shape.astype(int)))` so that the numpy can successfully create an empty array.

**Comment by mekman** [comment]
Thanks, fixed!
